### ISSUE TITLE
Uppercase missing when processing articles in series

### ISSUE THREAD

**Issue by vanch3d** [maforget/Bedetheque-Scrapper-2#6] opened 2021-08-23 13:06 UTC
With the current version (5.7.1), when a series name is processed to move the article (le, la ,les, l', The) at the end, the remaining name is not properly uppercased anymore.

Check for example this one: https://www.bedetheque.com/BD-Annee-des-quatre-empereurs-TL-Mai-68-369736.html

With `Formatted Articles (series)` checked and `Formatted titles` unchecked, the result of the scraper in the series field is `année des quatre empereurs (L')` instead of `Année des quatre empereurs (L')`

Note that if `Formatted titles` is checked, the series name is properly `Année Des Quatre Empereurs (L')`

**Comment by maforget** [comment] 2021-08-24 17:09
That's intended behavior, the `Formatted titles` option is meant to change the case of the Series or Title, The `Formatted Articles` option is only meant to move the article to the end, it isn't meant to change the case, in your example it keeps a small `a`, because that's they way it's written on the site. 

Did you except the first letter to be Uppercased when Formatting the articles?

**Comment by maforget** [comment] 2021-08-24 17:40
Fixed in f38ffca09680fe461498788ca0ae5fee74564fff

**Closed** 2021-08-24 18:11 UTC
